steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # # Run unit tests
  # - name: python
  #   entrypoint: python
  #   args: ["-m", "pytest", "--junitxml=${SHORT_SHA}_test_log.xml"] 

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'gcr.io/$PROJECT_ID/capstone:${SHORT_SHA}', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'gcr.io/$PROJECT_ID/capstone:${SHORT_SHA}']

  # Deploy to Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'capstone', 
           '--image=gcr.io/$PROJECT_ID/capstone:${SHORT_SHA}', 
           '--region', 'asia-southeast2', '--platform', 'managed', 
           '--allow-unauthenticated']
    timeout: 1800s
    

# # Save test logs to Google Cloud Storage
# artifacts:
#   objects:
#     location: gs://${_BUCKET_NAME}/
#     paths:
#       - ${SHORT_SHA}_test_log.xml
# # Store images in Google Artifact Registry 
# images:
#   - us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/myimage:${SHORT_SHA}